import sqlite3

DB_PATH = "hospital.db"

conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

cursor.execute("PRAGMA foreign_keys = ON")

cursor.execute("""
CREATE TABLE IF NOT EXISTS DIM_KHOAPHONG (
    ID_KHOAPHONG INTEGER PRIMARY KEY,
    TEN_KHOAPHONG TEXT NOT NULL,
    LOAI_KHOA TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS DIM_DICHVU (
    ID_DICHVU INTEGER PRIMARY KEY,
    TEN_DICHVU TEXT NOT NULL,
    LOAI_DICHVU TEXT,
    NHOM_DICHVU TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS DIM_DOITUONG (
    ID_DOITUONG INTEGER PRIMARY KEY,
    TEN_DOITUONG TEXT NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS DIM_LOAI_DIEUTRI (
    ID_LOAI_DIEUTRI INTEGER PRIMARY KEY,
    TEN_LOAI_DIEUTRI TEXT NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS DIM_BENHNHAN (
    ID_BENHNHAN TEXT PRIMARY KEY,
    HO_TEN TEXT,
    GIOI_TINH TEXT,
    NAM_SINH INTEGER
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS FACT_DOANHTHU (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NGAY TEXT NOT NULL,
    ID_BENHNHAN TEXT,
    ID_KHAMBENH TEXT,
    ID_KHOAPHONG INTEGER,
    ID_DICHVU INTEGER,
    ID_DOITUONG INTEGER,
    ID_LOAI_DIEUTRI INTEGER,
    SOLUONG INTEGER,
    DONGIA REAL,
    THANHTIEN REAL,
    BHYTTRA REAL,
    NGUOIBENHTRA REAL,
    CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ID_BENHNHAN) REFERENCES DIM_BENHNHAN(ID_BENHNHAN),
    FOREIGN KEY (ID_KHOAPHONG) REFERENCES DIM_KHOAPHONG(ID_KHOAPHONG),
    FOREIGN KEY (ID_DICHVU) REFERENCES DIM_DICHVU(ID_DICHVU),
    FOREIGN KEY (ID_DOITUONG) REFERENCES DIM_DOITUONG(ID_DOITUONG),
    FOREIGN KEY (ID_LOAI_DIEUTRI) REFERENCES DIM_LOAI_DIEUTRI(ID_LOAI_DIEUTRI)
)
""")

conn.commit()
conn.close()

print("Database initialized successfully.")
